-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            popups = true,
            special = true,
            xray = true,
        },
    },
    general = {
        col = {
            active_border = "0xff89fc92",
        },
    },
    misc = {
        vrr = 0,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})

-- Keybinds
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))
